all:
	gcc -o lock -Wall -lpthread lock.c
	gcc -o concurrent -Wall -lpthread concurrent.c
	gcc -o cv -Wall -lpthread cv.c
	gcc -o signal -Wall -lpthread signal.c


clean:
	rm -rf concurrent cv lock